name: update

on:
  schedule:
  - cron: '0 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: go build -v .
    - name: Upload executable
      uses: actions/upload-artifact@v1
      with:
        name: update
        path: android-repository-history
  update:
    name: Update
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download executable
      uses: actions/download-artifact@v1
      with:
        name: update
    - name: Update repository
      run: |
        ./android-repository-history
    - name: Publish
      run: |
        git remote -v
